#!/usr/bin/env node

/**
 * Vercel Build Script
 * This script runs during Vercel build to inject environment variables
 * into the frontend application
 */

const fs = require('fs');
const path = require('path');

console.log('🔧 Vercel Build: Injecting environment variables...');

// Get the backend URL from environment variable
const backendUrl = process.env.BACKEND_URL;

if (!backendUrl) {
    console.error('❌ ERROR: BACKEND_URL environment variable is not set!');
    console.error('Please add BACKEND_URL in Vercel project settings.');
    console.error('Example: https://freezingly-nonsignificative-edison.ngrok-free.dev');
    process.exit(1);
}

console.log(`✅ Backend URL: ${backendUrl}`);

// Create a runtime config file that will be loaded by the frontend
const configContent = `
// Auto-generated by Vercel build
window.BACKEND_URL = '${backendUrl}';
console.log('🌐 Vercel Environment: Backend URL configured');
`;

const configPath = path.join(__dirname, 'js', 'vercel-env.js');

try {
    fs.writeFileSync(configPath, configContent, 'utf8');
    console.log('✅ Created vercel-env.js with backend URL');
} catch (error) {
    console.error('❌ Failed to create vercel-env.js:', error);
    process.exit(1);
}

console.log('🎉 Build configuration complete!');
